### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by msidrisi91** [Robson/White-Noise-Image-Generator#4]
If you approve I can improve the UI. Make it two Column

**Comment by msidrisi91** [comment]
Something like this:
![1](https://user-images.githubusercontent.com/51527710/136701244-40b08247-96d8-4365-a0d5-26bc62796578.png)
![2](https://user-images.githubusercontent.com/51527710/136701247-ba693aff-122a-47d5-8648-735d3f91408c.png)

**Comment by Robson** [comment]
Hi Mohd

Thank you for the idea. It looks good! Some thoughts:

 * The tool must continue to work on mobile. Landscape and portrait. Happy to have a different layout per platform/orientation.
 * I ideally want to continue using consistent font-families across the site. Specifically that is Roboto Slab (titles only) and Rubik (anywhere). Can deviate from this if there is a significant benefit.
 * Very unsure about changing the background. That was purposefully chosen so that it would have no impact on viewing the generated images. Ideally the background would be black, white or grey.
